server:
  port: 8765

spring:
  application:
    name: edge-service

zuul:
  ignoredServices: "*"
  routes:
    order-service:
      sensitiveHeaders:
      path: /order/**
      serviceId: order-service
      stripPrefix: false
    item-service:
      sensitiveHeaders:
        path: /items/**
        serviceId: order-service
        stripPrefix: false

logging.level.org.springframework: trace
