server:
  servlet:
    context-path: /items
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:h2:mem:itemDb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      #http://localhost:8080/api/h2-console/
