server:
  servlet:
    context-path: /order
  port: 8082
  tomcat:
    max-http-post-size:

spring:
  datasource:
    url: jdbc:h2:mem:orderDb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      #http://localhost:8080/api/h2-console/
  application:
    name: order-service


  cloud:
    stream:
      kafka:
        binder:
          brokers: velomobile-01.srvs.cloudkafka.com:9094,velomobile-02.srvs.cloudkafka.com:9094,velomobile-03.srvs.cloudkafka.com:9094
          configuration:
            security.protocol: SASL_SSL
            sasl:
              mechanism: SCRAM-SHA-256
              jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="lv6ewheu" password="${PASSWORD}";
      bindings:
        output:
          destination: lv6ewheu-order

logging.level.org.springframework.cloud.stream: trace
